### ISSUE TITLE
🚀 [REQUEST] - Create 404 error page

### ISSUE THREAD

**Issue by hummingbbird** [AgainIoT/Open-Set-Go_client#126] opened 2023-10-16 11:46 UTC
### Describe

create a page to show when 404 error occurs

### Reasons

To create a more friendly page for users

### Connection

- [X] Have no effect on other functions
- [ ] Other functions need to be changed

**Comment by bentshrimp** [comment] 2023-10-17 03:41
Duplicate of #66

**Closed** 2023-10-18 11:16 UTC
Labels: feature-request
